In [1]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [2]:
# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S)
print(R)

[[ 1.76716709 -0.43287189 -0.68560239  1.0102908   0.48852788]
 [ 0.01047215 -0.2323369   0.21833742  1.38018061 -0.32582112]
 [-0.26784638 -0.11188163  0.64569597  1.30712025 -0.00495906]
 [-0.92631669  0.429123    0.10854802  0.04092055  0.10914579]
 [-0.12880651 -0.13687153 -1.04698477 -0.03308043 -0.57413357]]
[[ 0.97619746 -0.35872025]
 [-1.48255572 -2.65963041]
 [-0.01573082 -0.81944502]
 [ 1.99155989 -0.8845294 ]
 [ 1.26183815  1.10534664]]


In [3]:
# identity
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# zeros
Z = np.zeros((4,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]


In [6]:
# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(U)
print(L)

[[ 1.40116042 -1.7740028   0.60013688 -1.14076827  0.22421633]
 [ 0.         -0.24988344 -0.7315102   0.3751425   2.13907932]
 [ 0.          0.          0.77000563  0.69042489 -1.3392748 ]
 [ 0.          0.          0.         -0.10686659  0.64308018]
 [ 0.          0.          0.          0.          0.11789246]]
[[ 1.40116042  0.          0.          0.          0.        ]
 [ 0.91211865 -0.24988344  0.          0.          0.        ]
 [-0.42497567 -0.44390136  0.77000563  0.          0.        ]
 [-0.06228659 -0.89093883  0.85404897 -0.10686659  0.        ]
 [ 0.38777372  0.05369647 -0.14361431 -0.41598852  0.11789246]]


In [7]:
# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
#B = np.random.randn(4,4)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[-0.16794038  0.56826531  0.56503325  0.11406178 -0.28715714 -0.38254548]
 [ 2.11193739 -0.53422577  0.10641244  1.0821864  -0.01325258 -0.51341962]
 [ 0.95058893 -0.38181923 -0.51189936 -1.73764364  0.83615831 -1.54522747]]



---
# VIDEO: Matrix addition and subtraction
---


In [8]:
# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
# A+B
A+C

array([[-0.8516535 , -0.18596019,  0.15617013,  0.86308207],
       [ 1.14012269, -0.06945355,  1.3982311 , -0.72836958],
       [ 1.6189642 , -1.14278782, -0.21448021, -0.3336921 ],
       [ 1.24292062, -1.63943053, -1.03537079, -0.61168848],
       [-1.66953267,  0.47499385,  2.15450851,  1.04409471]])

In [9]:
# "shifting" a matrix
l = .3 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N).round(2)*100# can only shift a square matrix
print(D)

Ds = D + l*np.eye(N)
print(Ds)

[[  28.   59.  -22.  -55.  -37.]
 [  82.   77. -149.  -18.  -61.]
 [ -98.  -28.  -16.  112. -115.]
 [-134.  -30.  -13.   21.   -9.]
 [ 213.  -96. -144.  -46.  -62.]]
[[  28.3   59.   -22.   -55.   -37. ]
 [  82.    77.3 -149.   -18.   -61. ]
 [ -98.   -28.   -15.7  112.  -115. ]
 [-134.   -30.   -13.    21.3   -9. ]
 [ 213.   -96.  -144.   -46.   -61.7]]



---
# VIDEO: Matrix-scalar multiplication
---


In [11]:
# define matrix and scalar
M = np.array([ [1, 2], [3, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )

[[ 2  4]
 [ 6 10]]
[[ 2  4]
 [ 6 10]]


In [24]:
#Challenge
#is matrix scalar multiplication a linear operation? --> does it obey distributive trait
#is s(A+B) = sA + sB ? --> 빼서 0이 되면 되는것. 
M = np.random.randint(0, 10, 8).reshape(4,2)
N = np.random.randint(10, 20, 8).reshape(4,2)
S = 3

result1 = S * (M + N)
result2 = S*M + S*N

result1 - result2 == 0

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

# VIDEO: Transpose

In [25]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T),print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [28]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C))
print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# VIDEO: Diagonal and trace
---


In [30]:
np.random.seed(0)
M = np.round( 5*np.random.randn(4,4) )
print(M)
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

[[ 9.  2.  5. 11.]
 [ 9. -5.  5. -1.]
 [-1.  2.  1.  7.]
 [ 4.  1.  2.  2.]]
[ 9. -5.  1.  2.]
[[ 9.  0.  0.  0.]
 [ 0. -5.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  2.]]


In [31]:
# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr)
print(tr2)

7.0
7.0


In [41]:
#Challenge
#Linearity of trace
#tr(A+B) = tr(A) + tr(B) ?
#tr(l*A) = l*tr(A) ? (l is a random lambda)
np.random.seed(0)
A = np.random.randint(0,10, 8).reshape(2,4)
B = np.random.randint(10, 20, 8).reshape(2,4)
print(np.trace(A+B))
print(np.trace(A)+np.trace(B))
l = 0.3
print(np.trace(A*l))
print(np.trace(A)*l)


34
34
0.6
0.6
