In [1]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [5]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S)
print(R)

# identity
I = np.eye(3)
print(I)

# zeros
Z = np.zeros((4,4))
print(Z)

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D)

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(U)
print(L)

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
#B = np.random.randn(4,4)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[ 0.87023546 -0.30667709 -0.21455654  1.09809447 -0.91906232]
 [-0.40348341 -2.12547554 -0.04843861  0.30355335 -0.98850568]
 [ 2.13871134 -0.20545251  1.6177328   0.93552444 -0.45120151]
 [-0.04795964 -0.35944081 -0.27839001 -0.15042635  0.03806248]
 [-0.31438303  0.11251994 -1.34211211  0.37590981 -0.27912703]]
[[ 2.04482277 -0.71467549]
 [-0.7298587   1.16177503]
 [-0.47880759  0.14154672]
 [ 1.99242554 -0.91164307]
 [-0.84670409  0.24332809]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
[[-0.3252746  -1.50228345  0.52768214  1.94996609  0.78750469]
 [ 0.          0.09509194  0.59905791  1.45657469 -0.78407656]
 [ 0.          0.         -1.51382552 -0.10385279 -0.27177044]
 [ 0.          0.          0.         -0.42951368 -0.69853275]
 [ 0.          0.          0.          0.          0.87233206]]
[[-0.3252746   0.          0.          0.          0.        ]
 [ 0.


---
# VIDEO: Matrix addition and subtraction
---


In [3]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
A+B
A+C



# "shifting" a matrix
l = .3 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(Ds)

ValueError: operands could not be broadcast together with shapes (5,4) (5,3) 


---
# VIDEO: Matrix-scalar multiplication
---


In [43]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )

#Challenge
#is matrix scalar multiplication a linear operation? --> does it obey distributive trait
#is s(A+B) = sA + sB ? --> 빼서 0이 되면 되는것. 



[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


# VIDEO: Transpose

In [17]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T),print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [24]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# VIDEO: Diagonal and trace
---


In [10]:

M = np.round( 5*np.random.randn(4,4) )

# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr)
print(tr2)

#Challenge
#Linearity of trace
#tr(A+B) = tr(A) + tr(B) ?
#tr(l*A) = l*tr(A) ? (l is a random lambda)

[  4.  10.   4.   3.]
[[  4.   0.   0.   0.]
 [  0.  10.   0.   0.]
 [  0.   0.   4.   0.]
 [  0.   0.   0.   3.]]
21.0
21.0
