In [1]:
import sys
assert sys.version_info >= (3, 5)

# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "svm"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)

In [2]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

iris = datasets.load_iris()
X = iris["data"][:, (2,3)]
y = (iris["target"] == 2).astype(np.float64)

svm_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('linear_svc', LinearSVC(C=1, loss="hinge"))
])

svm_clf.fit(X, y)

Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('linear_svc',
                 LinearSVC(C=1, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
                           loss='hinge', max_iter=1000, multi_class='ovr',
                           penalty='l2', random_state=None, tol=0.0001,
                           verbose=0))],
         verbose=False)

In [3]:
svm_clf.predict([[5.5, 1.7]])

array([1.])

In [4]:
from sklearn.datasets import make_moons
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

X,y = make_moons(n_samples = 100, noise=0.15, random_state=42)
polynomial_svm_clf = Pipeline([
    ("poly_features", PolynomialFeatures(degree=3)),
    ("scaler", StandardScaler()),
    ("svm_clf", LinearSVC(C=10, loss="hinge"))
])
polynomial_svm_clf.fit(X,y)

D:\anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Pipeline(memory=None,
         steps=[('poly_features',
                 PolynomialFeatures(degree=3, include_bias=True,
                                    interaction_only=False, order='C')),
                ('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('svm_clf',
                 LinearSVC(C=10, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
                           loss='hinge', max_iter=1000, multi_class='ovr',
                           penalty='l2', random_state=None, tol=0.0001,
                           verbose=0))],
         verbose=False)

In [5]:
from sklearn.svm import SVC
poly_kernel_svm_clf = Pipeline([
    ("scaler", StandardScaler()),
    ('svm_clf', SVC(kernel="poly", degree=3, coef0=1, C=5))
])
# coef0 decides how much model is affected by higher degree or lower degree
# as the degree increase, the difference between a value higher than 1 and a value lower than one increases significantly.
# therefore, we want to minimize the gap using coef0

In [7]:
rbf_kernel_svm_clf = Pipeline([
    ("scaler", StandardScaler()),
    ('svm_clf', SVC(kernel="rbf", gamma=5, C=0.001))
])
rbf_kernel_svm_clf.fit(X,y)

Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('svm_clf',
                 SVC(C=0.001, break_ties=False, cache_size=200,
                     class_weight=None, coef0=0.0,
                     decision_function_shape='ovr', degree=3, gamma=5,
                     kernel='rbf', max_iter=-1, probability=False,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=False)

In [8]:
rbf_kernel_svm_clf.predict([[5.5, 1.7]])

array([1], dtype=int64)

In [13]:
np.random.seed(42)
m = 50
X = 2 * np.random.rand(m, 1)
y = (4 + 3 * X + np.random.randn(m, 1)).ravel()

In [21]:
from sklearn.svm import LinearSVR
svm_reg = LinearSVR(epsilon=0)
svm_reg.fit(X,y)

LinearSVR(C=1.0, dual=True, epsilon=0, fit_intercept=True,
          intercept_scaling=1.0, loss='epsilon_insensitive', max_iter=1000,
          random_state=None, tol=0.0001, verbose=0)

In [22]:
svm_reg.coef_

array([2.96304269])

In [23]:
svm_reg.intercept_

array([3.94274869])

In [24]:
y

array([ 6.98570729,  9.87565412,  8.27631537,  7.29084721,  3.45758985,
        4.21612291,  3.8878629 , 10.2541791 ,  7.95030836,  6.48539531,
        4.44759094,  9.43437683,  8.31773384,  5.88571095,  6.12194933,
        6.03170718,  4.98623593,  6.83932621,  6.92293354,  6.72291997,
        7.19194313,  4.65130419,  4.64653292,  5.00196444,  7.54894573,
       10.0672958 ,  5.12603257,  8.08893953,  7.91612344,  3.63358272,
        8.00666472,  6.56118131,  4.35448352, 11.25795688,  7.17404709,
        9.67228659,  5.91472968,  4.28702533,  8.19715894,  4.65334605,
        4.51255752,  7.32817403,  5.68422517,  8.93765219,  4.74418629,
        7.47337666,  6.78566857,  7.44915924,  6.75050147,  5.62239417])

In [25]:
svm_reg.predict(X)

array([6.16230541, 9.57676284, 8.28060729, 7.49044998, 4.86732847,
       4.86718554, 4.28695713, 9.07578248, 7.50500757, 8.13884724,
       4.06473416, 9.69051729, 8.87587485, 5.20108839, 5.02025897,
       5.02961947, 5.7457142 , 7.05250011, 6.50249175, 5.66859744,
       7.56864118, 4.76940122, 5.67402282, 6.11384025, 6.64545836,
       8.59576848, 5.12603257, 6.99014588, 7.45344801, 4.2180178 ,
       7.54311136, 4.95328921, 4.32824998, 9.5659254 , 9.66516656,
       8.7333804 , 5.74791589, 4.52156198, 7.99757203, 6.55112995,
       4.66595769, 6.87720934, 4.146538  , 9.33145903, 5.47630096,
       7.86891231, 5.78997514, 7.02471619, 7.18260048, 5.03821198])

In [26]:
from sklearn.svm import SVR
svm_poly_reg = SVR(kernel="poly", degree=2, C = 100, epsilon=0.1)
svm_poly_reg.fit(X,y)

SVR(C=100, cache_size=200, coef0=0.0, degree=2, epsilon=0.1, gamma='scale',
    kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False)